# Generated by Django 2.2.7 on 2019-11-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domein',
            old_name='domein_name',
            new_name='name',
        ),
    ]
