# Generated by Django 2.2.7 on 2019-11-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191106_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='domein',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='domein',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
                ('domein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Domein')),
            ],
        ),
    ]
